#
# Copyright (C) 2016 DANS - Data Archiving and Networked Services (info@dans.knaw.nl)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- hosts: "test"
  become: yes
  vars:
    local_test_vm_base_backend_port: 20110
  roles:
    - dans.local-test-vm-base
    - dans.local-yum-repo

- hosts: "test"
  become: yes
  tasks:
  - name: Create directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      mode: "0777"
    with_items:
        - /srv/dans.knaw.nl/bag-store
        - /srv/dans.knaw.nl/stage

  - name: Copy test-data to vm
    copy:
      src: ../../test/resources/bags/basic-sequence-unpruned-with-refbags/
      dest: /var/opt/dans.knaw.nl/tmp/easy-bag-store/examples/
      mode: "0777"

  - name: Create test-data archive
    archive:
      path: "/var/opt/dans.knaw.nl/tmp/easy-bag-store/examples/{{ item }}"
      dest: "/var/opt/dans.knaw.nl/tmp/easy-bag-store/examples/{{ item }}.zip"
      format: zip
      mode: "0777"
    with_items:
        - a
        - b
        - c

  - name: Install package
    yum:
      name: dans.knaw.nl-easy-bag-store
      state: latest

  - service:
      name: easy-bag-store
      state: started
      enabled: yes
